### ISSUE TITLE
logstash-cli version 0.0.7 doesn't work on ubuntu or centos5 after the latest update.

### ISSUE THREAD

**Issue by jedi4ever** [jedi4ever/logstash-cli#10]
@stevendanna I got this feedback from Brian - can you have a look? thanks!

logstash-cli version 0.0.7 doesn't work on ubuntu or centos5 after the latest update.
I had to revert back to 0.0.6 to get the same functionality.

I get this message

/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/logstash-cli-0.0.7/lib/logstash-cli/command/grep.rb:15: undefined (?...) sequence: /(?<value>\d+)\s*(?<units>\w*)/ (SyntaxError)
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
from /usr/lib/ruby/gems/1.8/gems/logstash-cli-0.0.7/lib/logstash-cli/command.rb:1
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
from /usr/lib/ruby/gems/1.8/gems/logstash-cli-0.0.7/lib/logstash-cli/cli.rb:11
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in`require'
from /usr/lib/ruby/gems/1.8/gems/logstash-cli-0.0.7/lib/logstash-cli.rb:3
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in `gem_original_require'
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in`require'
from /usr/lib/ruby/gems/1.8/gems/logstash-cli-0.0.7/bin/logstash-cli:2
from /usr/bin/logstash-cli:19:in `load'
from /usr/bin/logstash-cli:19

fixed logstash-cli by going back to version 0.0.6
gem install logstash-cli -v 0.0.6
gem uninstall logstash-cli -v 0.0.7

the following example command now works
logstash-cli grep hello

I know it's experimental but its a good project and I thought I can help.

**Comment by stevendanna** [comment]
My hunch is that I used some ruby 1.9 specific syntax.  I'll try to take a look sometime this week.  Thanks for pinging me.

**Comment by stevendanna** [comment]
A few things to fix here:
- Named captures (the "(?<value>\d+)" portion of the regex) are a 1.9 feature.
- The DateTime class in 1.8.7 doesn't support a number of the methods I use.

I'll start a branch to address these issues.

**Comment by jedi4ever** [comment]
@stevendanna thanks for taking care of that

**Comment by stevendanna** [comment]
I've just opened a pull request that "works for me" on 1.8.7 and 1.9.3.  If anyone is able to test and review the patch it would be greatly appreciated.

**Comment by bendrixx** [comment]
I was able to test and I get the below error.
centos5
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

When I run:

> logstash-cli

I get:

/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/logstash-cli-0.0.7/lib/logstash-cli/command/grep.rb:15: undefined (?...) sequence: /(?<value>\d+)\s*(?<units>\w*)/ (SyntaxError)
from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:55:in`require'

**Comment by stevendanna** [comment]
Is that using the version on rubygems or did you build a new gem from master?  From the error message it appears that you are still using the older code, before this pull request was accepted.

**Comment by bendrixx** [comment]
used gem install logstash-cli from rubygems just yesterday to install.

i will try to build from from master

**Comment by bendrixx** [comment]
verified fixed by building from master on centos5 with ruby 1.8.7.

thanks

**Comment by jedi4ever** [comment]
released a new gem version - sorry about the delay
